# Azure DevOps CI/CD Pipeline for Node.js Application

# Trigger pipeline on changes to the main branch
trigger:
- main

# Define the agent pool
pool:
  vmImage: 'ubuntu-latest'

# Define variables
variables:
  nodeVersion: '16.x' # Specify Node.js version
  azureSubscription: 'YourAzureSubscriptionName' # Replace with your Azure subscription name
  webAppName: 'YourWebAppName' # Replace with your Azure Web App name
  buildArtifact: 'dist' # Output directory for build

# Define pipeline steps
steps:
# Install Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '$(nodeVersion)'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Run build
- script: npm run build
  displayName: 'Build application'

# Run tests
- script: npm test
  displayName: 'Run unit tests'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathToPublish: '$(buildArtifact)'
    artifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/drop'
    deploymentMethod: 'auto'
